name: DNCNN_RubikConv
use_tb_logger: true
model_type: DNCNNModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
#### datasets

datasets:
  train:
    name: SIDD
    type: PairedImageDataset
    dataroot_gt: /SIDD/train_patch/target_crops
    dataroot_lq: /SIDD/train_patch/input_crops
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    use_flip: true
    use_rot: true
    gt_size: 224

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SIDD
    type: PairedImageDataset
    dataroot_gt: /SIDD/val/target_crops
    dataroot_lq: /SIDD/val/input_crops
    io_backend:
      type: disk

#### network structures
network_g:
  type: DNCNN_RubikConv
  in_nc: 3
  out_nc: 3
  nc: 96
  nb: 20
  shiftPixel: 1
  gc: 16

#### path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
#### training settings: learning rate scheme, loss

train:
  ema_decay: 0.0
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 150000, 250000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up
  dual: False

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: !!float 5000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~