# general settings
name: restormer_rubikCubeMul_denoising
model_type: RestormerModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 3407

# dataset and data loader settings
datasets:
  train:
    name: SIDD
    type: PairedImageDataset
    dataroot_gt: /SIDD/train_patch/target_crops
    dataroot_lq: /SIDD/train_patch/input_crops
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 128
    use_flip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SIDD
    type: PairedImageDataset
    dataroot_gt: /SIDD/val/target_crops
    dataroot_lq: /SIDD/val/input_crops
    io_backend:
      type: disk

network_g:
  type: Restormer_RubikConv
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4,6,6,8]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: BiasFree
  dual_pixel_task: False
  shiftPixel: 1

# path
path:
  pretrain_network_g: 
  strict_load_g: 
  resume_state: ~

# training settings
train:
  ema_decay: 0.0
  optim_g:
    type: Adam
    lr: !!float 3e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000, 250000]
    restart_weights: [1, 1]
    eta_min: !!float 1e-7

  total_iter: 500000
  warmup_iter: -1  # no warm up
  dual: False

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 50000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: False
      
# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 50000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500