name: MPRNet_rubikCube_deblur
use_tb_logger: true
model_type: MPRNetModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 3407
#### datasets

datasets:
  train:
    name: GoPro
    type: PairedImageDataset
    dataroot_gt: /motionDeblur/GoPro/train/target
    dataroot_lq: /motionDeblur/GoPro/train/input
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    use_flip: true
    use_rot: true
    gt_size: 128

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: GoPro
    type: PairedImageDataset
    dataroot_gt: /motionDeblur/GoPro/test/target
    dataroot_lq: /motionDeblur/GoPro/test/input
    io_backend:
      type: disk


#### network structures
# deblur
network_g:
  type: MPRNet_rubikCube
  in_c: 3
  out_c: 3
  n_feat: 96
  scale_unetfeats: 48
  scale_orsnetfeats: 32
  num_cab: 8
  kernel_size: 3
  reduction: 4
  shiftPixel: 1
  gc: 8


#### path
path:
# 
  pretrain_network_g: 
  strict_load_g: 
  resume_state: ~
#### training settings: learning rate scheme, loss

train:
  ema_decay: 0.0
  optim_g:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000, 250000]
    restart_weights: [1, 1]
    eta_min: !!float 1e-7

  total_iter: 500000
  warmup_iter: -1  # no warm up
  dual: False

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  edge_opt:
    type: EdgeLoss
    loss_weight: 0.0


val:
  val_freq: !!float 50000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false


#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 50000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~